// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpnizjpiorbxevyozmmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbml6anBpb3JieGV2eW96bW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDM3ODQsImV4cCI6MjA2NDM3OTc4NH0.KcP9L6C-BHvTcCxcV9R-Iui071w9XnymslR4aC8bhow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);